services:
  zmeta:
    build: .
    environment:
      ZMETA_ENV: dev
      ZMETA_CORS_ORIGINS: "http://localhost:3000"
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    command: ["uvicorn", "backend.app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
