name: Health Smoke Test

on:
  push:
    branches: [main]
  pull_request:

jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Smoke test health endpoint
        run: |
          set -euo pipefail
          python -m uvicorn backend.app.main:app --port 8001 --log-level warning &
          UVICORN_PID=$!
          trap 'kill $UVICORN_PID 2>/dev/null || true' EXIT
          for attempt in $(seq 1 15); do
            if python scripts/run_health_check.py --base-url http://127.0.0.1:8001 --output status; then
              echo "Health check succeeded on attempt $attempt"
              exit 0
            fi
            echo "Health check attempt $attempt failed; retrying..." >&2
            sleep 1
          done
          echo 'Health check failed after 15 attempts' >&2
          exit 1
